# Generated by Django 4.2.17 on 2025-01-21 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dlmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dlimage', versatileimagefield.fields.VersatileImageField(upload_to='dlimage/', verbose_name='Dlimage')),
                ('dlimage_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlmodels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dlmodel',
                'verbose_name_plural': 'Dlmodels',
                'ordering': ['created'],
            },
        ),
    ]
