# Generated by Django 4.2.17 on 2025-01-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlmodel',
            options={'ordering': ['created']},
        ),
    ]
