# Generated by Django 4.2.17 on 2025-01-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_dlmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlmodel',
            options={'ordering': ['created'], 'verbose_name': 'Dlmodel', 'verbose_name_plural': 'dlmodels'},
        ),
    ]
